from django.urls import path
from . import views
urlpatterns = [
   path('',views.index,name="index"),
   path('about/',views.about,name="about"),
   path('blog/',views.blog,name="blog"),
   path('petmart/',views.petmart,name="petmart"),
   path('petguide/',views.petguide,name="petguide"),
   path('contact/',views.contact,name="contact"),
   path('login/',views.login,name="login"),
   path('register/',views.register,name="register"),
   path('logout/',views.logout,name="logout"),
   path('myaccount/',views.myaccount,name="myaccount"),
   path('dog/',views.dog,name="dog"),
   path('cat/',views.cat,name="cat"),
   path('breed<id>/',views.breed,name="breed"),
   path('view<id>/',views.view,name="view"),
   path('deletepet<id>/',views.deletepet,name="deletepet"),
   path('editpet<id>/',views.editpet,name="editpet"),
   path('allpet/',views.allpet,name="allpet"),
   path('addpet/',views.addpet,name="addpet"),
   path('change_password/',views.change_password,name="change_password"),
   path('cart/<id>',views.cart,name="cart"),
   path('deletecartitem/<id>', views.deletecartitem,name='deletecartitem'),
   path('cartitem/', views.cartitem,name='cartitem'),
   path('buynow/<id>', views.buynow,name='buynow'),
   path('buynow1/<id>', views.buynow1,name='buynow1'),
   path('buyall/', views.buyall,name='buyall'),
   #path('blog/',views.blog,name="blog"),
]
