# Generated by Django 2.2.4 on 2019-11-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('dog', 'DOG'), ('cat', 'CAT')], default='dog', max_length=100)),
                ('breed', models.CharField(choices=[('labrador', 'LABRADOR'), ('bulldog', 'BULLDOG'), ('german_shepherd', 'GERMAN_SHERPHERD'), ('beagle', 'BEAGLE'), ('poodle', 'POODLE'), ('exotic_shorthair', 'EXOTIC_SHORTHAIR'), ('ragdoll', 'RAGDOLL'), ('british_shorthair', 'BRITISH_SHORTHAIR'), ('persian', 'PERSIAN'), ('maine_coon', 'MAINE_COON')], default='labrador', max_length=100)),
                ('price', models.IntegerField(null=True)),
                ('color', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('Image', models.ImageField(null=True, upload_to='shop/images')),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
