# Generated by Django 2.2.4 on 2019-11-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(choices=[('labrador', 'LABRADOR'), ('bulldog', 'BULLDOG'), ('german_shepherd', 'GERMAN_SHERPHERD'), ('beagle', 'BEAGLE'), ('poodle', 'POODLE'), ('exotic_shorthair', 'EXOTIC SHORTHAIR'), ('ragdoll', 'RAGDOLL'), ('british_shorthair', 'BRITISH SHORTHAIR'), ('persian', 'PERSIAN'), ('maine_coon', 'MAINE COON')], default='labrador', max_length=100),
        ),
    ]
