# Generated by Django 2.2.4 on 2019-11-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0002_auto_20191107_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('breed', models.CharField(max_length=100, null=True)),
                ('color', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('usern', models.CharField(max_length=100, null=True)),
                ('Image', models.ImageField(null=True, upload_to='shop/images')),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
