# Generated by Django 2.2.4 on 2019-11-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='pet_name',
            new_name='name',
        ),
    ]
