# Generated by Django 2.2.4 on 2019-11-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0004_auto_20191109_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=100)),
                ('address1', models.CharField(default='', max_length=100)),
                ('address2', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(choices=[('up', 'UP'), ('delhi', 'DELHI'), ('mp', 'MP'), ('maharastra', 'MAHARATRA'), ('gujrat', 'GUJRAT'), ('rajasthan', 'RAJASTHAN'), ('punjab', 'PUNJAB')], default='up', max_length=100)),
                ('zip_code', models.IntegerField(default='')),
                ('product_details', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
